- name: play level variables
  hosts: local
  connections: local
  vars:
   COURSE: ansible
   DURATION: 10HR
   TRAINER: sivakumar
  tasks:
  - name: print the course information 
    ansible.builtin.debug:
     msg: "hello {{ COURSE }}, course Duration: {{ DURATION }} , Trainer is : {{ TRAINER }}" 
  
  - name: print the course information agaim
    ansible.builtin.debug:
      msg: "hello {{ COURSE }}, course Duration: {{ DURATION }} , Trainer is : {{ TRAINER }}"