- name: variables from the inventory 
  hosts: frontend
  tasks:
  - name: course information 
    ansible.builtin.debug:
      msg:  "hello {{ COURSE }}, course Duration: {{ DURATION }} , Trainer is : {{ TRAINER }}" 